# For development purposes
# See docker-compose.prod-sample.yaml if you want to run the bot

version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: py_reportit_bot
      MYSQL_DATABASE: py_reportit_bot
      MYSQL_USER: py_reportit_bot
      MYSQL_PASSWORD: py_reportit_bot
    ports:
      - 3316:3306
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/py_reportit_bot.cnf

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=db
      - PMA_USER=py_reportit_bot
      - PMA_PASSWORD=py_reportit_bot
