version: '3.1'

services:
  db:
    image: mariadb:10.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: py_reportit_bot
      MYSQL_DATABASE: py_reportit_bot
      MYSQL_USER: py_reportit_bot
      MYSQL_PASSWORD: py_reportit_bot
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/py_reportit_bot.cnf
      - py_reportit_db:/var/lib/mysql

  py_reportit_crawler:
    image: py_reportit:latest
    restart: always
    depends_on:
      - db
    environment:
      - MIGRATE=1
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=py_reportit_bot
      - DB_PASSWORD=py_reportit_bot
      - DB_DATABASE=py_reportit_bot
      - TWITTER_API_KEY=xx
      - TWITTER_API_SECRET=xx
      - TWITTER_ACCESS_TOKEN=xx
      - TWITTER_ACCESS_SECRET=xx
    entrypoint: ["./wait-for-it.sh", "db:3306", "--", "./run_py_reportit_crawler.sh"]
    volumes:
      - py_reportit_photos:/app/photos

  py_reportit_api:
    image: py_reportit:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8090:80
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=py_reportit_bot
      - DB_PASSWORD=py_reportit_bot
      - DB_DATABASE=py_reportit_bot
    entrypoint: ["uvicorn", "py_reportit.web.server:app", "--host", "0.0.0.0", "--port", "80"]
    volumes:
      - py_reportit_photos:/app/photos

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 8081:15672
    environment:
      RABBITMQ_DEFAULT_USER: py_reportit_bot
      RABBITMQ_DEFAULT_PASS: py_reportit_bot
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  py_reportit_photos:
    external: true
    name: py_reportit_py_reportit_photos
  py_reportit_db:
    external: true
    name: py_reportit_py_reportit_db
  rabbitmq:
    external: true
    name: py_reportit_py_reportit_rabbitmq
