# Right now only for development purposes

version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: py_reportit_bot
      MYSQL_DATABASE: py_reportit_bot
      MYSQL_USER: py_reportit_bot
      MYSQL_PASSWORD: py_reportit_bot
    ports:
      - 3316:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=db
      - PMA_USER=py_reportit_bot
      - PMA_PASSWORD=py_reportit_bot
