"""Add type to answer meta tweet model

Revision ID: 025ae0f53687
Revises: c1ba9456086c
Create Date: 2021-12-10 22:23:27.130156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '025ae0f53687'
down_revision = 'c1ba9456086c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_meta_tweet', sa.Column('type', sa.Unicode(length=20), nullable=False))
    op.execute('UPDATE answer_meta_tweet SET type = "answer"')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer_meta_tweet', 'type')
    # ### end Alembic commands ###
