"""Remove modified count from CrawlResult model

Revision ID: 02e4575283cd
Revises: 7433e84fabed
Create Date: 2021-08-14 23:42:08.710341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02e4575283cd'
down_revision = '7433e84fabed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl_result', 'modified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_result', sa.Column('modified', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
