"""Add user model

Revision ID: 115a8a4ea7f8
Revises: f2d65e95b7d0
Create Date: 2022-03-06 16:35:54.992774

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql
from py_reportit.shared.util.localized_arrow import LocalizedArrow

# revision identifiers, used by Alembic.
revision = '115a8a4ea7f8'
down_revision = 'f2d65e95b7d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('username', sa.Unicode(length=100), nullable=False),
    sa.Column('password', sqlalchemy_utils.types.password.PasswordType(max_length=1137), nullable=False),
    sa.Column('created_at', LocalizedArrow(), nullable=False),
    sa.Column('admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
