"""Add address properties to report meta

Revision ID: 20ee38bd1124
Revises: 5a69174b2172
Create Date: 2021-11-03 18:54:45.701214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ee38bd1124'
down_revision = '5a69174b2172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta', sa.Column('address_polled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('meta', sa.Column('address_street', sa.String(length=100), nullable=True))
    op.add_column('meta', sa.Column('address_neighbourhood', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meta', 'address_neighbourhood')
    op.drop_column('meta', 'address_street')
    op.drop_column('meta', 'address_polled')
    # ### end Alembic commands ###
