"""Remove lat/lon stop positions from crawl, add reports data field

Revision ID: 2a1c73173985
Revises: d42f295baf1c
Create Date: 2024-03-17 13:00:42.098812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a1c73173985'
down_revision = 'd42f295baf1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl', sa.Column('reports_data', sa.JSON(), nullable=True))
    op.drop_column('crawl', 'stop_at_lon')
    op.drop_column('crawl', 'stop_at_lat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl', sa.Column('stop_at_lat', mysql.DECIMAL(precision=8, scale=6), nullable=True))
    op.add_column('crawl', sa.Column('stop_at_lon', mysql.DECIMAL(precision=9, scale=6), nullable=True))
    op.drop_column('crawl', 'reports_data')
    # ### end Alembic commands ###
