"""Report and Meta tables - initial creation

Revision ID: 3913545735d0
Revises: 
Create Date: 2021-08-09 17:25:05.122696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3913545735d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('tweeted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('photo_downloaded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('thumb_downloaded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta')
    # ### end Alembic commands ###
