"""Remove photo and thumbail urls from report, add has_photo

Revision ID: 3f0abbafe5a9
Revises: cc761196af26
Create Date: 2022-01-08 23:55:19.977015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f0abbafe5a9'
down_revision = 'cc761196af26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('has_photo', sa.Boolean(), nullable=True))
    op.execute('UPDATE report SET has_photo = 1 where photo_url IS NOT NULL')
    op.execute('UPDATE report SET has_photo = 0 where photo_url IS NULL')
    op.drop_column('report', 'thumbnail_url')
    op.drop_column('report', 'photo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('photo_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('report', sa.Column('thumbnail_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.drop_column('report', 'has_photo')
    # ### end Alembic commands ###
