"""Reintroduce crawl and crawl_item models

Revision ID: 4de60e84861c
Revises: eff35307e0af
Create Date: 2022-01-31 17:47:27.433418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de60e84861c'
down_revision = 'eff35307e0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('stop_at_lat', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('stop_at_lon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('current_task_id', sa.Unicode(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Enum('WAITING', 'PROCESSING', 'QUEUED', 'SUCCESS', 'FAILURE', 'SKIPPED', name='crawlitemstate'), nullable=False),
    sa.Column('report_found', sa.Boolean(), nullable=True),
    sa.Column('stop_condition_hit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crawl_item')
    op.drop_table('crawl')
    # ### end Alembic commands ###
