"""Add report answer and related meta models

Revision ID: 627451339463
Revises: 02e4575283cd
Create Date: 2021-08-27 18:24:41.367963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627451339463'
down_revision = '02e4575283cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('author', sa.Unicode(length=100), nullable=True),
    sa.Column('text', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_answer_id', sa.Integer(), nullable=False),
    sa.Column('tweeted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['report_answer_id'], ['report_answer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_meta')
    op.drop_table('report_answer')
    # ### end Alembic commands ###
