"""Extend Meta model by is_online, add CrawlResult model

Revision ID: 7433e84fabed
Revises: f59c3dad9acd
Create Date: 2021-08-14 15:58:50.268631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7433e84fabed'
down_revision = 'f59c3dad9acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('added', sa.Integer(), nullable=True),
    sa.Column('removed', sa.Integer(), nullable=True),
    sa.Column('modified', sa.Integer(), nullable=True),
    sa.Column('marked_done', sa.Integer(), nullable=True),
    sa.Column('highest_id', sa.Integer(), nullable=True),
    sa.Column('lowest_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('meta', sa.Column('is_online', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meta', 'is_online')
    op.drop_table('crawl_result')
    # ### end Alembic commands ###
