"""Add 'order' field to answer model

Revision ID: 8dc6ad3a2a7c
Revises: dbb7e7345368
Create Date: 2021-08-29 15:41:22.383107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc6ad3a2a7c'
down_revision = 'dbb7e7345368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_answer', sa.Column('order', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_answer', 'order')
    # ### end Alembic commands ###
