"""Add address properties to report meta - postcode

Revision ID: c1ba9456086c
Revises: 20ee38bd1124
Create Date: 2021-11-04 16:50:02.530086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ba9456086c'
down_revision = '20ee38bd1124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta', sa.Column('address_postcode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meta', 'address_postcode')
    # ### end Alembic commands ###
