"""Add do_tweet switch for reports and answers

Revision ID: c9b03285f2b7
Revises: e6dad483ff97
Create Date: 2021-09-07 14:17:54.632599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b03285f2b7'
down_revision = 'e6dad483ff97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_meta', sa.Column('do_tweet', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('meta', sa.Column('do_tweet', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meta', 'do_tweet')
    op.drop_column('answer_meta', 'do_tweet')
    # ### end Alembic commands ###
