"""Add last login field to user model

Revision ID: d42f295baf1c
Revises: 115a8a4ea7f8
Create Date: 2022-03-06 23:32:36.493534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from py_reportit.shared.util.localized_arrow import LocalizedArrow

# revision identifiers, used by Alembic.
revision = 'd42f295baf1c'
down_revision = '115a8a4ea7f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', LocalizedArrow(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###
