"""Add crawl and crawl_item models

Revision ID: e63d193f2885
Revises: 360f5f8b459a
Create Date: 2022-01-26 17:59:33.752656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63d193f2885'
down_revision = '360f5f8b459a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('stop_at_lat', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('stop_at_lon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('current_task_id', sa.Unicode(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Enum('WAITING', 'SUCCESS', 'FAILURE', name='crawlitemstate'), nullable=False),
    sa.Column('report_found', sa.Boolean(), nullable=True),
    sa.Column('stop_condition_hit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crawl_item')
    op.drop_table('crawl')
    # ### end Alembic commands ###
