"""Add tweet models for report and answer metas

Revision ID: e6dad483ff97
Revises: 8dc6ad3a2a7c
Create Date: 2021-08-29 22:59:54.218669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6dad483ff97'
down_revision = '8dc6ad3a2a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Unicode(length=20), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('tweet_id', sa.Unicode(length=30), nullable=False),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer_meta_tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_meta_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('tweet_id', sa.Unicode(length=30), nullable=False),
    sa.ForeignKeyConstraint(['answer_meta_id'], ['answer_meta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_meta_tweet')
    op.drop_table('meta_tweet')
    # ### end Alembic commands ###
