"""Temporarily drop crawl and crawlitem models

Revision ID: eff35307e0af
Revises: 3151e0810aa7
Create Date: 2022-01-31 17:44:41.170201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eff35307e0af'
down_revision = '3151e0810aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crawl_item')
    op.drop_table('crawl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_item',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('crawl_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('report_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('scheduled_for', mysql.DATETIME(), nullable=False),
    sa.Column('state', mysql.ENUM('WAITING', 'SUCCESS', 'FAILURE'), nullable=False),
    sa.Column('report_found', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('stop_condition_hit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl.id'], name='crawl_item_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('crawl',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('scheduled_at', mysql.DATETIME(), nullable=False),
    sa.Column('stop_at_lat', mysql.DECIMAL(precision=8, scale=6), nullable=True),
    sa.Column('stop_at_lon', mysql.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('current_task_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
