"""Add category voting models

Revision ID: f2d65e95b7d0
Revises: 4de60e84861c
Create Date: 2022-02-20 16:09:42.830181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy_utils.types.uuid import UUIDType
from py_reportit.shared.util.localized_arrow import LocalizedArrow

# revision identifiers, used by Alembic.
revision = 'f2d65e95b7d0'
down_revision = '4de60e84861c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Unicode(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_vote',
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('user_id', UUIDType(binary=False), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', LocalizedArrow(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.id'], ),
    sa.PrimaryKeyConstraint('meta_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_vote')
    op.drop_table('category')
    # ### end Alembic commands ###
