"""Report and Meta tables - initial creation

Revision ID: f59c3dad9acd
Revises: 
Create Date: 2021-08-12 18:08:50.873779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59c3dad9acd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('photo_url', sa.String(length=100), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('key_category', sa.String(length=100), nullable=True),
    sa.Column('id_service', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Unicode(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('tweeted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('photo_downloaded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('thumb_downloaded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta')
    op.drop_table('report')
    # ### end Alembic commands ###
